const JOB_REQUEST="JOB_REQUEST"
const JOB_SUCCESS="JOB_SUCCESS"
const JOB_FAILED="JOB_FAILED"


const MOVIE_REQUEST="MOVIE_REQUEST"
const MOVIE_SUCCESS="MOVIE_SUCCESS"
const MOVIE_FAILED="MOVIE_FAILED"

export {
    JOB_REQUEST,
    JOB_SUCCESS,
    JOB_FAILED,

    MOVIE_REQUEST,
    MOVIE_SUCCESS,
    MOVIE_FAILED
}