
import './globals.css'
import 'animate.css';
import 'material-icons/iconfont/material-icons.css';
import { Inter } from 'next/font/google';
// import store from '@/components/store';
// import { Provider } from 'react-redux';
import Providers from '@/components/provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
     
          <html lang="en">
          <body className={inter.className}>
            <Providers>
             
              {children}
            </Providers> 
          </body>
          </html>
      
  )
}
